# Generated by Django 5.2 on 2025-04-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='type',
            field=models.CharField(choices=[('beans', 'Beans'), ('maize', 'Maize'), ('g-nuts', 'Groundnuts'), ('soybeans', 'Soybeans'), ('cowpeas', 'Cowpeas')], max_length=100),
        ),
    ]
