# Generated by Django 5.2 on 2025-05-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_amount_paid_sale_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
    ]
