# Generated by Django 5.2 on 2025-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale_change_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
