# Generated by Django 5.2 on 2025-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sale_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='unit',
        ),
        migrations.AlterField(
            model_name='sale',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
