# Generated by Django 5.2 on 2025-05-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
    ]
